Fixes guest add and edit errors
View helpers have been removed or the api changed, so I just used strings to fix
the following error:

`undefined method `content_tag'`